version: "3.9"

volumes:
  config:
  prom-rules:
  promxy-shared:
  relabel-rules:
  grafana-data:
  alertmanager:
  tsdb:
  rdb:
  graph:
  search:
  fluentd:

services:
  # Frontend
  asserts-ui:
    image: asserts/asserts-ui:latest
    container_name: asserts-ui
    restart: on-failure
    depends_on:
      - "asserts-server"
      - "fluentd"
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: asserts-ui

  # Backend
  asserts-server:
    image: asserts/asserts-server:latest
    container_name: asserts-server
    restart: on-failure
    depends_on:
      - "grafana"
      - "postgres"
      - "promxyruler"
      - "redisgraph"
      - "redisearch"
      - "fluentd"
    ports:
      - 8030:8030
    volumes:
      - config:/opt/asserts/config
      - prom-rules:/opt/asserts/prom-rules
      - relabel-rules:/opt/asserts/relabel-rules
      - promxy-shared:/opt/asserts/promxy-shared:rw
      - ./:/opt/asserts/license/
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      - LICENSE_FILE_LOCATION=/var # update this location
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: asserts-server

  authorization:
    image: asserts/authorization:latest
    container_name: authorization
    depends_on:
      - "postgres"
      - "fluentd"
    ports:
      - 8070:8070
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      - LICENSE_FILE_LOCATION=/var # update this location
    volumes:
      - ./:/opt/asserts/license/
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: asserts-server

  grafana:
    image: asserts/grafana:latest
    container_name: grafana
    user: grafana
    restart: always
    depends_on:
      - "promxyuser"
      - "fluentd"
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana/data
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: grafana

  # Vendor
  alertmanager:
    image:  asserts/alertmanager:latest
    container_name: alertmanager
    restart: always
    depends_on:
      - "fluentd"
    ports:
      - 9093:9093
    volumes:
      - alertmanager:/alertmanager:rw
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: alertmanager

  promxyruler:
    image: asserts/promxy:latest
    container_name: promxyruler
    restart: always
    depends_on:
      - "victoriametrics"
      - "alertmanager"
      - "fluentd"
    ports:
      - 8082:8082
    command:
      - --config=/opt/asserts/promxy-shared/promxyruler-config.yaml
      - --web.enable-lifecycle
      - --log-level=info
    volumes:
      - promxy-shared:/opt/asserts/promxy-shared:ro
      - prom-rules:/opt/asserts/rules
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: promxyruler

  promxyuser:
    image: asserts/promxy:latest
    container_name: promxyuser
    restart: always
    depends_on:
      - "victoriametrics"
      - "fluentd"
    ports:
      - 8083:8082
    command:
      - --config=/opt/asserts/promxy-shared/promxyuser-config.yaml
      - --web.enable-lifecycle
      - --log-level=info
    volumes:
      - promxy-shared:/opt/asserts/promxy-shared:ro
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: promxyuser

  victoriametrics:
    image: asserts/victoria-metrics:latest
    container_name: victoriametrics
    restart: always
    depends_on:
      - "fluentd"
    ports:
      - 8428:8428
    volumes:
      - tsdb:/storage:rw
      - relabel-rules:/etc/asserts:ro
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: victoriametrics

  postgres:
    image: asserts/postgres:latest
    container_name: postgres
    restart: on-failure
    depends_on:
      - "fluentd"
    ports:
      - 5432
    volumes:
      - rdb:/var/lib/postgresql/data:rw
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: victoriametrics

  redisearch:
    image: asserts/redisearch:latest
    container_name: redisearch
    restart: on-failure
    depends_on:
      - "fluentd"
    volumes:
      - search:/data:rw
    ports:
      - 6380:6379
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: redisearch

  redisgraph:
    image: asserts/redisgraph:latest
    container_name: redisgraph
    restart: on-failure
    depends_on:
      - "fluentd"
    volumes:
      - graph:/data:rw
    ports:
      - 6379:6379
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: redisearch

  # Monitoring
  redisearch-exporter:
    image: asserts/redisearch-exporter:latest
    container_name: redisearch-exporter
    restart: on-failure
    ports:
      - 9121

  redisgraph-exporter:
    image: asserts/redisgraph-exporter:latest
    container_name: redisgraph-exporter
    restart: on-failure
    ports:
      - 9121

  postgres-exporter:
    image: asserts/postgres-exporter:latest
    container_name: postgres-exporter
    restart: on-failure
    ports:
      - 9187

  fluentd:
    image: asserts/fluentd:latest
    container_name: fluentd
    restart: on-failure
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - fluentd:/fluentd/log

  collect-logs:
    image: asserts/collect-logs:latest
    volumes:
      - fluentd:/fluentd/log
      - ./:/logs
    profiles:
      - tools