version: '3'
services:
  motorhead:
    x-omnistrate-capabilities:
      customDNS:
        targetPort: 8080
    image: ghcr.io/getmetal/motorhead:v2.0.1
    volumes:
      - source: file_system_data
        target: /var/lib/motorhead/data
        type: volume
        x-omnistrate-storage:
          aws:
            clusterStorageType: AWS::EFS
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      PORT: 8080
      MOTORHEAD_MAX_WINDOW_SIZE: 25
      MOTORHEAD_LONG_TERM_MEMORY: 'true'
      MOTORHEAD_MODEL: 'gpt-3.5-turbo'
      REDIS_URL: 'redis://redis:6379'
    x-omnistrate-actionhooks:
      - scope: CLUSTER
        type: INIT
        commandTemplate: |
          echo "Action Hook Executed for scope: CLUSTER and type: INIT"
      - scope: NODE
        type: INIT
        command:
        - /bin/sh
        - -c
        commandTemplate: |
          echo "Action Hook Executed for scope: NODE and type: INIT"
      - scope: CLUSTER
        type: ADD
        commandTemplate: |
          echo "Action Hook Executed for scope: CLUSTER and type: ADD"
      - scope: NODE
        type: ADD
        commandTemplate: |
          echo "Action Hook Executed for scope: NODE and type: ADD"
      - scope: CLUSTER
        type: REMOVE
        commandTemplate: |
          echo "Action Hook Executed for scope: CLUSTER and type: REMOVE"
      - scope: NODE
        type: REMOVE
        commandTemplate: |
          echo "Action Hook Executed for scope: NODE and type: REMOVE"
      - scope: CLUSTER
        type: PROMOTE
        commandTemplate: |
          echo "Action Hook Executed for scope: CLUSTER and type: PROMOTE"
      - scope: NODE
        type: PROMOTE
        commandTemplate: |
          echo "Action Hook Executed for scope: NODE and type: PROMOTE"
      - scope: CLUSTER
        type: DEMOTE
        commandTemplate: |
          echo "Action Hook Executed for scope: CLUSTER and type: DEMOTE"
      - scope: NODE
        type: DEMOTE
        commandTemplate: |
          echo "Action Hook Executed for scope: NODE and type: DEMOTE"
      - scope: CLUSTER
        type: HEALTH_CHECK
        commandTemplate: |
          echo "Action Hook Executed for scope: CLUSTER and type: HEALTH_CHECK"
      - scope: NODE
        type: HEALTH_CHECK
        commandTemplate: |
          echo "Action Hook Executed for scope: NODE and type: HEALTH_CHECK"
      - scope: CLUSTER
        type: POST_START
        commandTemplate: |
          echo "Action Hook Executed for scope: CLUSTER and type: POST_START"
      - scope: NODE
        type: POST_START
        commandTemplate: |
          echo "Action Hook Executed for scope: NODE and type: POST_START"

  redis:
    image: redis/redis-stack-server:6.2.6-v7
    volumes:
      - source: file_system_data
        target: /var/lib/redis/data
        type: volume
        x-omnistrate-storage:
          aws:
            clusterStorageType: AWS::EFS
    ports:
      - '6379:6379'
    x-omnistrate-mode-internal: true


volumes:
  file_system_data:
    driver: sharedFileSystem
    driver_opts:
      efsThroughputMode: elastic
      efsPerformanceMode: generalPurpose