apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $sys.id }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/postgres