version: '3.9'
x-omnistrate-service-plan:
  name: "Custom Sidecar OTEL"
  tenancyType: "OMNISTRATE_DEDICATED_TENANCY"
  deployment:
    hostedDeployment:
      AwsAccountId: 'xxxxxxxxxx'
      AwsBootstrapRoleAccountArn: 'arn:aws:iam::xxxxxxxxxx:role/omnistrate-bootstrap-role'
      GcpProjectId: 'xxxxxxxxxx'
      GcpProjectNumber: 'xxxxxxxxxx'
      GcpServiceAccountEmail: 'xxxxxxxxxx@xxxxxxxxxx.iam.gserviceaccount.com'
      AzureSubscriptionId: 'xxxxxxxxxx'
      AzureTenantId: 'xxxxxxxxxx'
services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      - SECURITY_CONTEXT_USER_ID=999
      - SECURITY_CONTEXT_GROUP_ID=999
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/dbdata
    configs:
      - source: otel-config
        target: /mnt/otel-config.yaml
    volumes:
      - ./data:/var/lib/postgresql/data
    x-omnistrate-capabilities:
      serviceAccountPolicies:
        aws:
          - CLOUDWATCH
      sidecars:
        otel:
          imageNameWithTag: "otel/opentelemetry-collector-contrib:0.116.1"
          command:
            - "/otelcol-contrib"
            - "--config"
            - "/mnt/otel-config.yaml"
          resourceLimits:
            cpu: "250m"
            memory: "256Mi"
          securityContext:
            runAsUser: 10001
            runAsGroup: 0
            runAsNonRoot: true
            capabilities:
              add:
              - SYS_RESOURCE

configs:
  otel-config:
    name: otel-config
    file: ./resources/otel-config.yaml
