version: '3.9'


x-omnistrate-service-plan:
  name: "PG with custom networks"
  tenancyType: "OMNISTRATE_DEDICATED_TENANCY"
  features:
    CUSTOM_NETWORKS:
  deployment:
    hostedDeployment:
      AwsAccountId: 'xxxxxxxxxx'
      AwsBootstrapRoleAccountArn: 'arn:aws:iam::xxxxxxxxxx:role/omnistrate-bootstrap-role'
      GcpProjectId: 'xxxxxxxxxx'
      GcpProjectNumber: 'xxxxxxxxxx'
      GcpServiceAccountEmail: 'xxxxxxxxxx@xxxxxxxxxx.iam.gserviceaccount.com'
      AzureSubscriptionId: 'xxxxxxxxxx'
      AzureTenantId: 'xxxxxxxxxx'
      
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - SECURITY_CONTEXT_USER_ID=999
      - SECURITY_CONTEXT_GROUP_ID=999
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/dbdata
    volumes:
      - ./data:/var/lib/postgresql/data