version: '3.9'
x-omnistrate-service-plan:
  name: "OTEL Observability"
  tenancyType: "OMNISTRATE_DEDICATED_TENANCY"
  deployment:
    hostedDeployment:
      awsAccountId: '<AWS_ACCOUNT_ID>'
      awsBootstrapRoleAccountArn: 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/omnistrate-bootstrap-role'
      gcpProjectId: '<GCP_PROJECT_ID>'
      gcpProjectNumber: '<GCP_PROJECT_NUMBER>'
      gcpServiceAccountEmail: '<GCP_SERVICE_ACCOUNT_EMAIL>'
      azureSubscriptionId: '<AZURE_SUBSCRIPTION_ID>'
      azureTenantId: '<AZURE_TENANT_ID>'
x-internal-integrations:
  metrics:
    provider: newRelic
    endpoint: https://otlp.nr-data.net
    secretLocators:
      aws: arn:aws:secretsmanager:<REGION>:<AWS_ACCOUNT_ID>:secret:<SECRET_PATH>
      gcp: projects/<GCP_PROJECT_NUMBER>/secrets/<SECRET_NAME>/versions/latest
      azure: OmnistrateE2ETests/NewRelicAPIKey # Vault in "Dev Dataplane - Service Provider Hosted" subscription
    serviceComponentsConfiguration:
      promexporter:
        prometheusEndpoint: "http://localhost:8080/metrics"
  logs:
    provider: newRelic
    endpoint: https://otlp.nr-data.net
    secretLocators:
      aws: arn:aws:secretsmanager:<REGION>:<AWS_ACCOUNT_ID>:secret:<SECRET_PATH>
      gcp: projects/<GCP_PROJECT_NUMBER>/secrets/<SECRET_NAME>/versions/latest
      azure: OmnistrateE2ETests/NewRelicAPIKey # Vault in "Dev Dataplane - Service Provider Hosted" subscription
services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      - SECURITY_CONTEXT_USER_ID=999
      - SECURITY_CONTEXT_GROUP_ID=999
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/dbdata
    volumes:
      - ./data:/var/lib/postgresql/data
  promexporter:
    image: quay.io/brancz/prometheus-example-app:v0.5.0
    ports:
      - '8080'
    x-omnistrate-mode-internal: true
