version: '3.9'
x-omnistrate-service-plan:
  name: "OTEL Observability"
  tenancyType: "OMNISTRATE_DEDICATED_TENANCY"
  deployment:
    hostedDeployment:
      AwsAccountId: 'xxxxxxxxxx'
      AwsBootstrapRoleAccountArn: 'arn:aws:iam::xxxxxxxxxx:role/omnistrate-bootstrap-role'
      GcpProjectId: 'xxxxxxxxxx'
      GcpProjectNumber: 'xxxxxxxxxx'
      GcpServiceAccountEmail: 'xxxxxxxxxx@xxxxxxxxxx.iam.gserviceaccount.com'
      AzureSubscriptionId: 'xxxxxxxxxx'
      AzureTenantId: 'xxxxxxxxxx'
x-internal-integrations:
  metrics:
    provider: newRelic
    endpoint: https://otlp.nr-data.net
    secretLocators:
      aws: arn:aws:secretsmanager:ap-south-1:339713121445:secret:dev/observability/new-relic-oSCbN8
      gcp: projects/61114262792/secrets/NewRelicLicenseKey/versions/latest
      azure: OmnistrateE2ETests/NewRelicAPIKey # Vault in "Dev Dataplane - Service Provider Hosted" subscription
    serviceComponentsConfiguration:
      promexporter:
        prometheusEndpoint: "http://localhost:8080/metrics"
  logs:
    provider: newRelic
    endpoint: https://otlp.nr-data.net
    secretLocators:
      aws: arn:aws:secretsmanager:ap-south-1:339713121445:secret:dev/observability/new-relic-oSCbN8
      gcp: projects/61114262792/secrets/NewRelicLicenseKey/versions/latest
      azure: OmnistrateE2ETests/NewRelicAPIKey # Vault in "Dev Dataplane - Service Provider Hosted" subscription
services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      - SECURITY_CONTEXT_USER_ID=999
      - SECURITY_CONTEXT_GROUP_ID=999
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/dbdata
    volumes:
      - ./data:/var/lib/postgresql/data
  promexporter:
    image: quay.io/brancz/prometheus-example-app:v0.5.0
    ports:
      - '8080'
    x-omnistrate-mode-internal: true
