version: '3.9'
x-omnistrate-service-plan:
  name: "OTEL Observability BYOC"
  tenancyType: "OMNISTRATE_DEDICATED_TENANCY"
  deployment:
    byoaDeployment:
      AwsAccountId: 'xxxxxxxxxx'
      AwsBootstrapRoleAccountArn: 'arn:aws:iam::xxxxxxxxxx:role/omnistrate-bootstrap-role'
x-internal-integrations:
  metrics:
    provider: native
    serviceComponentsConfiguration:
    promexporter:
      prometheusEndpoint: "http://localhost:8080/metrics"
  logs:
    provider: native
services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      - SECURITY_CONTEXT_USER_ID=999
      - SECURITY_CONTEXT_GROUP_ID=999
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/dbdata
    volumes:
      - ./data:/var/lib/postgresql/data
    x-omnistrate-compute:
      instanceTypes:
        - cloudProvider: azure
          name: Standard_B2ms
  promexporter:
    image: quay.io/brancz/prometheus-example-app:v0.5.0
    ports:
      - '8080'
    x-omnistrate-mode-internal: true
