version: '3'
services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootPass
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - db_conf:/etc/mysql
volumes:
  db_data: null
  db_conf: null
