version: "3.9"

x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics

services:
  cassandra_seed:
    x-omnistrate-api-params:
      - key: clusterName
        description: Cassandra cluster name
        name: Cluster Name
        type: String
        modifiable: true
        required: true
        export: true
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - source: cassandra_seed
        target: /var/lib/cassandra
        type: bind
        x-omnistrate-storage:
          aws:
            instanceStorageType: AWS::EBS_GP3
            instanceStorageSizeGi: 10
            instanceStorageIOPS: 3000
            instanceStorageThroughputMiBps: 125
          gcp:
            instanceStorageType: GCP::PD_BALANCED
            instanceStorageSizeGi: 10
          azure:
            instanceStorageType: AZURE::PREMIUM_SSD
            instanceStorageSizeGi: 10
    environment:
      - "CASSANDRA_CLUSTER_NAME=$var.clusterName"
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    x-omnistrate-compute:
      instanceTypes:
        - name: t3.medium
          cloudProvider: aws
        - name: e2-medium
          cloudProvider: gcp
        - name: Standard_B2als_v2
          cloudProvider: azure
    x-omnistrate-capabilities:
      autoscaling:
        minReplicas: 1
        maxReplicas: 5
      enableMultiZone: true
    x-omnistrate-mode-internal: true

  Cassandra:
    image: cassandra:latest
    ports:
      - "9043:9042"
    volumes:
      - source: cassandra_data
        target: /var/lib/cassandra
        type: bind
        x-omnistrate-storage:
          aws:
            instanceStorageType: AWS::EBS_GP3
            instanceStorageSizeGi: 10
            instanceStorageIOPS: 3000
            instanceStorageThroughputMiBps: 125
          gcp:
            instanceStorageType: GCP::PD_BALANCED
            instanceStorageSizeGi: 10
          azure:
            instanceStorageType: AZURE::PREMIUM_SSD
            instanceStorageSizeGi: 10
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=$var.clusterName"
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    x-omnistrate-compute:
      instanceTypes:
        - name: t3.medium
          cloudProvider: aws
        - name: e2-medium
          cloudProvider: gcp
        - name: Standard_B2als_v2
          cloudProvider: azure
    depends_on:
      cassandra_seed:
        condition: service_healthy
    x-omnistrate-api-params:
      - key: clusterName
        description: Name of the Cassandra cluster
        name: Cluster Name
        type: String
        modifiable: true
        required: true
        export: true
        parameterDependencyMap:
          cassandra_seed: clusterName
    x-omnistrate-capabilities:
      autoscaling:
        minReplicas: 1
        maxReplicas: 5
      enableMultiZone: true
    x-omnistrate-mode-internal: false

