version: "3.9"

x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics

# Visit app.falkordb.cloud to try different instance types and more!

services:
  Falkordb:
    image: falkordb/falkordb:edge
    x-omnistrate-compute:
      instanceTypes:
        - name: t3.medium
          cloudProvider: aws
        - name: e2-medium
          cloudProvider: gcp
        - name: Standard_B2als_v2
          cloudProvider: azure
    volumes:
      - source: ./falkordb-data
        target: /data
        type: bind
        x-omnistrate-storage:
          aws:
            instanceStorageType: AWS::EBS_GP3
            instanceStorageSizeGi: 10
            instanceStorageIOPS: 3000
            instanceStorageThroughputMiBps: 125
          gcp:
            instanceStorageType: GCP::PD_BALANCED
            instanceStorageSizeGi: 10
          azure:
            instanceStorageType: AZURE::PREMIUM_SSD
            instanceStorageSizeGi: 10
    x-omnistrate-api-params:
      - key: falkordbPassword
        description: FalkorDB Password
        name: FalkorDB Password
        type: Password
        modifiable: false
        required: true
        export: false
    environment:
      - REDIS_PASSWORD=$var.falkordbPassword
      - SECURITY_CONTEXT_USER_ID=0
      - SECURITY_CONTEXT_GROUP_ID=0
      - SECURITY_CONTEXT_FS_GROUP=0
    ports:
      - "6379:6379"
    x-omnistrate-capabilities:
      enableMultiZone: true
