version: "3.9"

x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics

services:
  PGAdmin:
    image: omnistrate/pgadmin4:7.5
    ports:
      - 80:80
    volumes:
      - ./data:/var/lib/pgadmin
    x-omnistrate-compute:
      instanceTypes:
        - name: t3.medium
          cloudProvider: aws
        - name: e2-medium
          cloudProvider: gcp
        - name: Standard_B2als_v2
          cloudProvider: azure
    x-omnistrate-capabilities:
      autoscaling:
        minReplicas: 1
        maxReplicas: 2
      httpReverseProxy:
        targetPort: 80
      enableMultiZone: true
      enableEndpointPerReplica: true
    environment:
      - DB_ENDPOINT=Writer
      - SECURITY_CONTEXT_FS_GROUP=0
      - SECURITY_CONTEXT_USER_ID=0
      - SECURITY_CONTEXT_GROUP_ID=0
      - PGADMIN_DEFAULT_EMAIL=$var.email
      - PGADMIN_SERVER_JSON_FILE=/tmp/servers.json
      - PGADMIN_DEFAULT_PASSWORD=$var.password
      - DB_USERNAME=$var.dbUser
    x-omnistrate-api-params:
      - key: email
        description: PGAdmin Email Address
        name: Email
        type: String
        export: true
        required: true
        modifiable: false
      - key: password
        description: PGAdmin Password
        name: Password
        type: Password
        export: false
        required: true
        modifiable: false
      - key: dbUser
        description: Default DB Username
        name: DB Username
        type: String
        modifiable: false
        required: true
        export: true
      - key: instanceType
        description: Instance Type for the PGAdmin cluster
        name: Instance Type
        type: String
        modifiable: true
        required: true
        export: true
    x-omnistrate-mode-internal: true
  Writer:
    image: omnistrate/pgvector:c227409
    ports:
      - 5432:5432
    volumes:
      - source: ./data
        target: /var/lib/postgresql/data
        type: bind
        x-omnistrate-storage:
          aws:
            instanceStorageType: AWS::EBS_GP3
            instanceStorageSizeGi: 10
            instanceStorageIOPSAPIParam: instanceStorageIOPS
            instanceStorageThroughputAPIParam: instanceStorageThroughput
          gcp:
            instanceStorageType: GCP::PD_BALANCED
            instanceStorageSizeGi: 10
          azure:
            instanceStorageType: AZURE::PREMIUM_SSD
            instanceStorageSizeGi: 10
    x-omnistrate-compute:
      instanceTypes:
        - cloudProvider: aws
          apiParam: writerInstanceType
        - cloudProvider: gcp
          apiParam: writerInstanceType
        - cloudProvider: azure
          apiParam: writerInstanceType
    x-omnistrate-capabilities:
      enableEndpointPerReplica: true
    environment:
      - POSTGRESQL_PASSWORD=$var.postgresqlPassword
      - POSTGRESQL_DATABASE=$var.postgresqlDatabase
      - POSTGRESQL_USERNAME=$var.postgresqlUsername
      - POSTGRESQL_POSTGRES_PASSWORD=$var.postgresqlRootPassword
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_DATA_DIR=/var/lib/postgresql/data/dbdata
      - SECURITY_CONTEXT_USER_ID=1001
      - SECURITY_CONTEXT_FS_GROUP=1001
      - SECURITY_CONTEXT_GROUP_ID=0
    x-omnistrate-api-params:
      - key: writerInstanceType
        description: Writer Instance Type
        name: Writer Instance Type
        type: String
        modifiable: true
        required: true
        export: true
      - key: postgresqlPassword
        description: Default DB Password
        name: Password
        type: Password
        modifiable: false
        required: true
        export: false
      - key: postgresqlDatabase
        description: Default DB Name
        name: Default Database
        type: String
        modifiable: false
        required: true
        export: true
      - key: postgresqlUsername
        description: Username
        name: Default DB Username
        type: String
        modifiable: false
        required: true
        export: true
      - key: postgresqlRootPassword
        description: Root Password
        name: Root DB Password
        type: Password
        modifiable: false
        required: false
        export: false
        defaultValue: rootpassword12345
      - key: instanceStorageIOPS
        description: Instance Storage IOPS; Applicable to AWS only
        name: Instance Storage IOPS
        type: Float64
        modifiable: true
        required: true
        export: true
      - key: instanceStorageThroughput
        description: Instance Storage Throughput (in MB /s); Applicable to AWS only
        name: Instance Storage Throughput
        type: Float64
        modifiable: true
        required: true
        export: true
    x-omnistrate-actionhooks:
      - scope: CLUSTER
        type: INIT
        commandTemplate: >
          PGPASSWORD={{ $var.postgresqlRootPassword }} psql -U postgres
          -h writer {{ $var.postgresqlDatabase }} -c "create extension vector"
    x-omnistrate-mode-internal: true
  Reader:
    image: omnistrate/pgvector:c227409
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    x-omnistrate-compute:
      replicaCountAPIParam: numReadReplicas
      instanceTypes:
        - cloudProvider: aws
          apiParam: readerInstanceType
        - cloudProvider: gcp
          apiParam: readerInstanceType
        - cloudProvider: azure
          apiParam: readerInstanceType
    x-omnistrate-capabilities:
      enableMultiZone: true
      enableEndpointPerReplica: true
    environment:
      - POSTGRESQL_PASSWORD=$var.postgresqlPassword
      - POSTGRESQL_MASTER_HOST=Writer
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_DATA_DIR=/var/lib/postgresql/data/dbdata
      - SECURITY_CONTEXT_USER_ID=1001
      - SECURITY_CONTEXT_FS_GROUP=1001
      - SECURITY_CONTEXT_GROUP_ID=0
    x-omnistrate-api-params:
      - key: readerInstanceType
        description: Reader Instance Type
        name: Reader Instance Type
        type: String
        modifiable: true
        required: true
        export: true
      - key: postgresqlPassword
        description: Default DB Password
        name: Password
        type: Password
        modifiable: false
        required: true
        export: false
      - key: postgresqlUsername
        description: Username
        name: Default DB Username
        type: String
        modifiable: false
        required: true
        export: true
      - key: numReadReplicas
        description: Number of Read Replicas
        name: Number of Read Replicas
        type: Float64
        modifiable: true
        required: true
        export: true
    x-omnistrate-mode-internal: true
  FerretDB:
    image: ghcr.io/ferretdb/ferretdb:1.13.0
    ports:
      - 27017:27017
    volumes:
      - ./ferretdb:/state
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://writer:5432/{{ $var.dbName }}
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        modifiable: true
        required: true
        export: true
        parameterDependencyMap:
          Writer: writerInstanceType
          Reader: readerInstanceType
          PGAdmin: instanceType
      - key: postgresqlPassword
        description: Default DB Password
        name: Password
        type: Password
        modifiable: false
        required: true
        export: false
        parameterDependencyMap:
          Writer: postgresqlPassword
          Reader: postgresqlPassword
          PGAdmin: password
      - key: postgresqlUsername
        description: Username
        name: Default DB Username
        type: String
        modifiable: false
        required: true
        export: true
        parameterDependencyMap:
          Writer: postgresqlUsername
          Reader: postgresqlUsername
          PGAdmin: dbUser
      - key: pgadminEmailAddress
        description: PGAdmin Email Address
        name: PGAdmin Email Address
        type: String
        modifiable: false
        required: true
        export: true
        parameterDependencyMap:
          PGAdmin: email
      - key: dbName
        description: Default Database Name
        name: Default Database
        type: String
        modifiable: false
        required: true
        export: true
        parameterDependencyMap:
          Writer: postgresqlDatabase
      - key: numReadReplicas
        description: Number of Read Replicas
        name: Number of Read Replicas
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "1"
        parameterDependencyMap:
          Reader: numReadReplicas
      - key: writerInstanceStorageIOPS
        description: Writer Instance Storage IOPS; Applicable to AWS only
        name: Writer Instance Storage IOPS
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "3000"
        parameterDependencyMap:
          Writer: instanceStorageIOPS
      - key: writerInstanceStorageThroughput
        description: Writer Instance Storage Throughput (in MB /s); Applicable to AWS only
        name: Writer Instance Storage Throughput
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "125"
        parameterDependencyMap:
          Writer: instanceStorageThroughput
    depends_on:
      - Writer
      - Reader
      - PGAdmin
    x-omnistrate-mode-internal: false
