version: "3.9"

x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics

services:
  prometheus:
    image: docker.io/omnistrate/prometheus-demo:v1
    volumes:
      - source: ./prometheus_data
        target: /prometheus
        type: bind
        x-omnistrate-storage:
          aws:
            instanceStorageType: AWS::EBS_GP3
            instanceStorageSizeGi: 10
            instanceStorageIOPS: 3000
            instanceStorageThroughputMiBps: 125
          gcp:
            instanceStorageType: GCP::PD_BALANCED
            instanceStorageSizeGi: 10
          azure:
            instanceStorageType: AZURE::PREMIUM_SSD
            instanceStorageSizeGi: 10
    environment:
      - SCRAPE_INTERVAL=10s
      - EVALUATION_INTERVAL=10s
      - TARGETS=$var.targets
      - SECURITY_CONTEXT_USER_ID=65534
      - SECURITY_CONTEXT_GROUP_ID=65534
      - SECURITY_CONTEXT_FS_GROUP=65534
    ports:
      - "9090:9090"
    x-omnistrate-capabilities:
      httpReverseProxy:
        targetPort: 9090
      enableEndpointPerReplica: true
    restart: unless-stopped
    x-omnistrate-api-params:
      - key: targets
        description: CSV of targets
        name: Targets to scrape
        type: String
        modifiable: true
        required: true
        export: true
        defaultValue: "localhost:9090"
