version: "3.9"

x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    x-omnistrate-capabilities:
      autoscaling:
        maxReplicas: 1
        minReplicas: 1
        idleMinutesBeforeScalingDown: 20
        idleThreshold: 1
        overUtilizedMinutesBeforeScalingUp: 3
        overUtilizedThreshold: 80
      enableMultiZone: true
      serverlessConfiguration:
        enableAutoStop: true
        minimumNodesInPool: 1
        targetPort: 6379