version: "3.9"

x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics

services:
  proton-server:
    image: ghcr.io/timeplus-io/proton:1.5.2-rc
    ports:
      - "8123:8123"
      - "3218:3218"
      - "8463:8463"
      - "9000:9000"
    x-omnistrate-compute:
      instanceTypes:
        - apiParam: instanceType
          cloudProvider: aws
        - apiParam: instanceType
          cloudProvider: gcp
        - apiParam: instanceType
          cloudProvider: azure
    environment:
      - STREAM_STORAGE_BROKERS=stream-store:9092
      - STREAM_STORAGE_QUEUE_BUFFERING_MAX_MS=$var.storageQueueBuffering
      - STREAM_STORAGE_FETCH_WAIT_MAX_MS=$var.storageFetchWait
      - STREAM_STORAGE_TYPE=kafka
      - STREAM_STORAGE_CLUSTER_ID=default-sys-kafka-cluster-id
      - STREAM_STORAGE_SECURITY_PROTOCOL=PLAINTEXT
      - ENABLE_LOG_STREAM=true
    volumes:
      - ./data:/var/lib/proton/data
    x-omnistrate-mode-internal: true
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type for the Proton service
        name: Proton Instance Type
        type: String
        modifiable: true
        required: true
        export: true
      - key: storageQueueBuffering
        description: Max storage queue buffering in milliseconds
        name: Storage queue buffering (ms)
        type: Float64
        modifiable: true
        required: true
        export: true
      - key: storageFetchWait
        description: Max storage fetch wait in milliseconds
        name: Storage fetch wait (ms)
        type: Float64
        modifiable: true
        required: true
        export: true

  stream-store:
    image: mbianchidev143/redpanda:v23.2.26
    ports:
      - "9092:9092"
      - "29092:29092"
      - "8082:8082"
      - "8081:8081"
      - "9644:9644"
    x-omnistrate-compute:
      instanceTypes:
        - apiParam: instanceType
          cloudProvider: aws
        - apiParam: instanceType
          cloudProvider: gcp
        - apiParam: instanceType
          cloudProvider: azure
    environment:
      - SECURITY_CONTEXT_USER_ID=0
      - SECURITY_CONTEXT_GROUP_ID=0
      - SECURITY_CONTEXT_FS_GROUP=0
    volumes:
      - ./data:/var/lib/redpanda/data
    x-omnistrate-mode-internal: true
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type for the Redpanda service
        name: Redpanda Instance Type
        type: String
        modifiable: true
        required: true
        export: true

  Timeplus-Cluster:
    image: omnistrate/noop
    depends_on:
      - proton-server
      - stream-store
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        modifiable: true
        required: true
        export: true
        parameterDependencyMap:
          proton-server: instanceType
          stream-store: instanceType
      - key: storageQueueBuffering
        description: Max storage queue buffering in milliseconds
        name: Storage queue buffering (ms)
        type: Float64
        modifiable: true
        required: true
        export: true
        defaultValue: "50"
        parameterDependencyMap:
          proton-server: storageQueueBuffering
      - key: storageFetchWait
        description: Max storage fetch wait in milliseconds
        name: Storage fetch wait (ms)
        type: Float64
        modifiable: true
        required: true
        export: true
        defaultValue: "500"
        parameterDependencyMap:
          proton-server: storageFetchWait
    x-omnistrate-mode-internal: false
